name: bitcoin_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10               
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - cffi                     
  - plotly 
  - pip
  - pip:
    - yfinance                
    - tensorflow              
    - curl_cffi               
    - streamlit